version: "3.2"
services:

  auth_service:
    command: node src/server.js
    build:
      context: ./auth
      dockerfile: ../Dockerfile
    ports:
      - ${AUTH_PORT}:3000
    volumes:
      - ./auth:/app/
      - /app/node_modules
    environment:
      JWT_SECRET: ${JWT_SECRET}

  movies_service:
    command: npm run start:debug
    build:
      context: ./movies
      dockerfile: ../Dockerfile
    ports:
      - ${MOVIES_PORT}:3000
      - 9229:9229
    volumes:
      - ./movies:/app/
      - /app/node_modules
    environment:
      JWT_SECRET: ${JWT_SECRET}
